export default {
    namespaced: true,
    // -----------------------------------------------------------------
    state: {
        icons:[
        'mdi-access-point',
        'mdi-account',
        'mdi-account-alert',
        'mdi-account-arrow-right',
        'mdi-account-box',
        'mdi-account-cash',
        'mdi-account-check',
        'mdi-account-child',
        'mdi-account-circle',
        'mdi-account-clock',
        'mdi-account-convert',
        'mdi-account-details',
        'mdi-account-edit',
        'mdi-account-group',
        'mdi-account-heart',
        'mdi-account-key',
        'mdi-account-lock',
        'mdi-account-minus',
        'mdi-account-multiple',
        'mdi-account-multiple-outline',
        'mdi-account-off',
        'mdi-account-plus',
        'mdi-account-question',
        'mdi-account-remove',
        'mdi-account-search',
        'mdi-account-settings',
        'mdi-account-star',
        'mdi-account-supervisor',
        'mdi-account-tie',
        'mdi-account-tie-voice',
        'mdi-adjust',
        'mdi-air-conditioner',
        'mdi-air-filter',
        'mdi-air-horn',
        'mdi-air-humidifier',
        'mdi-air-purifier',
        'mdi-airbag',
        'mdi-airballoon',
        'mdi-airplane',
        'mdi-airplane-landing',
        'mdi-airplane-off',
        'mdi-airplane-takeoff',
        'mdi-airplay',
        'mdi-airport',
        'mdi-alarm',
        'mdi-alarm-bell',
        'mdi-alarm-light',
        'mdi-alarm-note',
        'mdi-alarm-snooze',
        'mdi-album',
        ],
    },
    getters: {
        getIcons(state){
            return state.icons
        },
    }
}